site_name: illia
site_description: "illia, your Bayesian NN library of choice"
repo_name: EricssonResearch/illia
repo_url: https://github.com/EricssonResearch/illia
site_url: ""
copyright: © Telefonaktiebolaget LM Ericsson 1994-2025

nav:
  - Home:
      - User guide: index.md
  - PyTorch Reference:
      - illia.torch.distributions: torch/distributions/distributions.md
      - illia.torch.nn: torch/nn/nn.md
      - illia.torch.nn_geom: torch/nn_geom/nn_geom.md
  - Tensorflow Reference:
      - illia.tf.distributions: tf/distributions/distributions.md
      - illia.tf.nn: tf/nn/nn.md

theme:
  name: "material"
  locale: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - toc.follow
  logo: assets/images/logo_black.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo_black_small.png

use_directory_urls: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            summary:
              attributes: false
              functions: false
              modules: false
              classes: true
            merge_init_into_class: true
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_bases: false
            show_root_full_path: false
            show_symbol_type_heading: true
            show_special_methods: false
            show_symbol_type_toc: true
            modernize_annotations: true

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ericsson/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ericsson
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ericsson

extra_css:
  - assets/css/custom.css
