name: Build MkDocs for GitHub Pages
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: ./.github/actions/setup-python-env

    - name: Set cache ID
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      shell: bash

    - name: Configure cache
      uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - name: Upload content to GitHub on gh-deploy branch
      run: mkdocs gh-deploy --config-file ./mkdocs.yml --force
      shell: bash
