name: Setup Python Environment
description: Sets up Python and dependencies
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"
        # Caching pip dependencies
        cache: "pip"

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-wiki.txt
