name: Lint Illia Code

inputs:
  src-project-folder:
    description: "Directory where the project is located"
    required: true
    default: "src"

runs:
  using: composite
  steps:
    - name: Check format with Black
      run: |
        echo "Running Black formatter check..."  
        uv run black --check ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Lint with flake8
      run: |
        echo "Running Flake8 linter..."
        uv run flake8 ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Code quality with Pylint
      run: |
        echo "Running Pylint linter..."
        uv run pylint --fail-under=8 ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Cognitive Complexity with complexipy
      run: |
        echo "Running complexipy..."
        uv run complexipy ${{ inputs.src-project-folder }}/
      shell: bash

    - name: Check Mypy
      run: |
        echo "Running Mypy type checker..."
        uv run mypy ${{ inputs.src-project-folder }}/
      shell: bash
