name: Test Illia Code

# Define inputs for the action, such as the project folder and the tests folder
inputs:
  src-tests-folder:
    description: "Directory where the project tests are located"
    required: true
    default: "tests"

runs:
  using: composite
  steps:
    # Step 1: Run tests using Pytest
    - name: Pytest
      run: |
        echo "Running tests with Pytest..."
        uv run pytest ${{ inputs.src-tests-folder }}/
      shell: bash
