name: Obtain Version
description: Get Package Version from version.py File

inputs:
  src-project-folder:
    description: "Project Directory"
    required: true
    default: "src"

outputs:
  version:
    description: "Package Version"
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get Package Version
      id: get_version
      shell: bash
      run: |
        VERSION=$(uv run python -c "from ${{ inputs.src-project-folder }} import version; print(version.__version__)")
        echo "version=v$VERSION" >> $GITHUB_OUTPUT
        echo "Package Version: v$VERSION"
