"""
This module implements  the Evidence Lower Bound
(ELBO) loss for Bayesian neural networks in PyTorch.
"""

# Standard libraries
from typing import Any

# 3pps
import torch

# Own modules
from illia.losses.torch.kl import KLDivergenceLoss


class ELBOLoss(torch.nn.Module):
    """
    Computes the Evidence Lower Bound (ELBO) loss function for
    Bayesian neural networks.

    This combines a reconstruction loss and a KL divergence term,
    estimated using Monte Carlo sampling.
    """

    def __init__(
        self,
        loss_function: torch.nn.Module,
        num_samples: int = 1,
        kl_weight: float = 1e-3,
        **kwargs: Any,
    ) -> None:
        """
        Initializes the ELBO loss with sampling and KL scaling.

        Args:
            loss_function: Module for computing reconstruction loss.
            num_samples: Number of MC samples for estimation.
            kl_weight: Weight applied to the KL loss.

        Returns:
            None.
        """

        # Call super class constructor
        super().__init__(**kwargs)

        # Set attributes
        self.loss_function = loss_function
        self.num_samples = num_samples
        self.kl_weight = kl_weight
        self.kl_loss = KLDivergenceLoss(weight=kl_weight)

    def forward(
        self, outputs: torch.Tensor, targets: torch.Tensor, model: torch.nn.Module
    ) -> torch.Tensor:
        """
        Compute the ELBO loss using Monte Carlo sampling and KL regularization.

        Args:
            outputs: Predictions generated by the model.
            targets: Ground truth values for training.
            model: Model containing Bayesian layers.

        Returns:
            Scalar representing the average ELBO loss.
        """

        loss_value = torch.tensor(
            0, device=next(model.parameters()).device, dtype=torch.float32
        )

        for _ in range(self.num_samples):
            loss_value += self.loss_function(outputs, targets) + self.kl_loss(model)

        loss_value /= self.num_samples

        return loss_value
