nav:
  - Home: index.md
  - API: api/
  - Examples: examples/
  - Reference:
      - Bayesian Neural Networks: reference/bayesian_neural_networks.md
      - Bibliography: reference/bibliography.md
  - Ericsson Cognitive Labs: https://ericsson.github.io/cognitive-labs/

sort:
  ignore_case: true
  type: alphabetical
