nav:
  - Home: index.md
  - Frameworks: frameworks/
  - Examples: examples/
  - Reference:
      - Bayesian Neural Networks: reference/bayesian_neural_networks.md
      - Bibliography: reference/bibliography.md

sort:
  ignore_case: true
  type: alphabetical
