name: Illia Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main", "dev"]

# Set up environment variables
env:
  # Folder where the project code is located
  SRC_PROJECT_FOLDER: "illia"
  # Folder where test files are located
  SRC_PROJECT_TESTS: "tests/torch"
  # Python version to use
  SRC_PYTHON_VERSION: "3.11"

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Create different jobs for each unit of work, in this case
# one to build and test the project, and another to do the deployment
# to GitHub Pages
jobs:
  setup-lint-test:
    # Name of the job
    name: Setup, Lint and Test Illia Code
    # Operating system to be used in the job
    runs-on: ubuntu-latest

    # Sequence of steps to be used in the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment and install dependencies for
      # testing and linting
      - name: Setup Python environment and dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{ env.SRC_PYTHON_VERSION }}

      # Step 3: Run code linting to check code style, syntax, and quality
      # using Black, MyPy and Flake8
      - name: Check code format, syntax and quality
        uses: ./.github/actions/lint-code
        with:
          src-project-folder: ${{ env.SRC_PROJECT_FOLDER }}

      # Step 4: Run tests using PyTest in the project
      - name: Test code
        uses: ./.github/actions/test-code
        with:
          src-tests-folder: ${{ env.SRC_PROJECT_TESTS }}

  build-mkdocs:
    name: Build MkDocs Illia Wiki
    runs-on: ubuntu-latest
    needs: setup-lint-test

    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment and install dependencies for
      # documentation
      - name: Setup Python environment and dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{ env.SRC_PYTHON_VERSION }}

      # Step 3: Build the MkDocs site
      - name: Build MkDocs
        uses: ./.github/actions/build-mkdocs