name: Illia Workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Runs on PR targeting the default branch
  pull_request:
    branches:
      - main

  # Allows run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Create different jobs for each unit of work, in this case
# one to build and test the project, and another to do the deployment
# to GitHub Pages
jobs:

  # Name of the job
  build:
    name: Build Illia
    # Operating system to be used in the job
    runs-on: ubuntu-latest

    # Sequence of steps to be used in the job
    steps:
      - name: Build Illia
        uses: ./.github/actions/build-application

  test:
    name: Lint and Test Illia
    needs: build
    runs-on: ubuntu-latest

    # Sequence of steps to be used in the job
    steps:
      - name: Lint Illia
        uses: ./.github/actions/lint

      - name: Test Illia
        uses: ./.github/actions/test

  deploy:

    name: Deploy Illia MKDocs Wiki to GitHub pages
    # To do the deployment of the documentation we depend on creating
    # and testing the library earlier
    needs: test

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Illia on GitHub Pages
        uses: ./.github/actions/deployment