name: Illia Workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Runs on PR targeting the default branch
  pull_request:
    branches:
      - main

  # Allows run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Create different jobs for each unit of work, in this case
# one to build and test the project, and another to do the deployment
# to GitHub Pages
jobs:
  setup:
    # Name of the job
    name: Setup Python
    # Operating system to be used in the job
    runs-on: ubuntu-latest
    # Sequence of steps to be used in the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint Illia Code
        uses: ./.github/actions/lint

  test:
    name: Test Code
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test Illia Code
        uses: ./.github/actions/test

  build-wiki:
    name: Build MkDocs Illia
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build MkDocs
        uses: ./.github/actions/build-mkdocs

  deploy-wiki:
    name: Deploy Wiki to GitHub pages
    runs-on: ubuntu-latest
    needs: build-wiki

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
