"""
This module implements  the Evidence Lower Bound
(ELBO) loss for Bayesian neural networks in Jax.
"""

# Standard libraries
from typing import Any, Callable

# 3pps
import jax
import jax.numpy as jnp
from flax import nnx

# Own modules
from illia.losses.jax.kl import KLDivergenceLoss


class ELBOLoss(nnx.Module):
    """
    Computes the Evidence Lower Bound (ELBO) loss function.

    Combines a reconstruction loss and the KL divergence using
    Monte Carlo sampling.
    """

    def __init__(
        self,
        loss_function: Callable[[jax.Array, jax.Array], jax.Array],
        num_samples: int = 1,
        kl_weight: float = 1e-3,
        **kwargs: Any,
    ) -> None:
        """
        Initializes the ELBO loss with sampling and KL scaling.

        Args:
            loss_function: Module for computing reconstruction loss.
            num_samples: Number of MC samples for estimation.
            kl_weight: Weight applied to the KL loss.

        Returns:
            None.
        """

        # Call super class constructor
        super().__init__(**kwargs)

        # Set attributes
        self.loss_function = loss_function
        self.num_samples = num_samples
        self.kl_weight = kl_weight
        self.kl_loss = KLDivergenceLoss(weight=kl_weight)

    def __call__(
        self, outputs: jax.Array, targets: jax.Array, model: nnx.Module
    ) -> jax.Array:
        """
        Computes the ELBO loss using MC sampling and KL regularization.

        Args:
            outputs: Predictions generated by the model.
            targets: Ground truth values for training.
            model: Model containing Bayesian modules.

        Returns:
            Average ELBO loss as a scalar array.
        """

        loss_value: jax.Array = jnp.array(0.0)
        for _ in range(self.num_samples):
            loss_value += self.loss_function(outputs, targets) + self.kl_loss(model)

        loss_value /= self.num_samples

        return loss_value
