# Standard libraries
from typing import Any, Callable

# 3pps
import jax
import jax.numpy as jnp
from flax import nnx

# Own modules
from illia.losses.jax.kl import KLDivergenceLoss


class ELBOLoss(nnx.Module):
    """
    Computes the Evidence Lower Bound (ELBO) loss for Bayesian networks.
    The ELBO loss combines a reconstruction loss with a KL divergence
    term. Monte Carlo sampling can be used to estimate the expected
    reconstruction loss over the model's stochastic layers.

    Notes:
        The KL term is weighted by `kl_weight`. This module assumes the
        model contains Bayesian layers compatible with
        `KLDivergenceLoss`.
    """

    def __init__(
        self,
        loss_function: Callable[[jax.Array, jax.Array], jax.Array],
        num_samples: int = 1,
        kl_weight: float = 1e-3,
        **kwargs: Any,
    ) -> None:
        """
        Initialize the ELBO loss with sampling and KL regularization.

        Args:
            loss_function: Function for computing reconstruction loss.
            num_samples: Number of Monte Carlo samples for estimation.
            kl_weight: Weight applied to the KL divergence term.
            **kwargs: Additional arguments passed to the base class.

        Returns:
            None.
        """

        # Call super class constructor
        super().__init__(**kwargs)

        # Set attributes
        self.loss_function = loss_function
        self.num_samples = num_samples
        self.kl_weight = kl_weight
        self.kl_loss = KLDivergenceLoss(weight=kl_weight)

    def __call__(
        self, outputs: jax.Array, targets: jax.Array, model: nnx.Module
    ) -> jax.Array:
        """
        Compute the ELBO loss using Monte Carlo sampling and KL
        regularization.

        Args:
            outputs: Predictions generated by the model.
            targets: Ground truth values for training.
            model: Model containing Bayesian layers.

        Returns:
            Scalar array representing the average ELBO loss.

        Notes:
            The loss is averaged over `num_samples` Monte Carlo draws.
        """

        loss_value: jax.Array = jnp.array(0.0)
        for _ in range(self.num_samples):
            loss_value += self.loss_function(outputs, targets) + self.kl_loss(model)

        loss_value /= self.num_samples

        return loss_value
